# How to load data

# 0. Example dataset
## Pima Indians Dataset
- A population of women who were at least 21 years old, of Pima Indian heritage and living near Phoenix, Arizona, was tested for diabetes according to World Health Organization criteria.
- The data were collected by the US National Institute of Diabetes and Digestive and Kidney Diseases.
- https://archive.ics.uci.edu/ml/datasets/Pima+Indians+Diabetes

# 1. Read the data file in local

## Using pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Using pandas.read_csv()
# Pandas는 여러 형태의 파일을 불러들일 수 있습니다.
# pd.read_ 이후에 [TAB]을 눌러 여러 함수들이 있음을 확인

# 파일에 변수 이름이 같이 있는 경우, header = True를 통해 한 번에 변수명을 불러들일 수 있음.

data = pd.read_csv('data/pima-indians-diabetes.data', header = None)

In [3]:
data

0    1   2   3    4     5      6   7  8
0     6  148  72  35    0  33.6  0.627  50  1
1     1   85  66  29    0  26.6  0.351  31  0
2     8  183  64   0    0  23.3  0.672  32  1
3     1   89  66  23   94  28.1  0.167  21  0
4     0  137  40  35  168  43.1  2.288  33  1
5     5  116  74   0    0  25.6  0.201  30  0
6     3   78  50  32   88  31.0  0.248  26  1
7    10  115   0   0    0  35.3  0.134  29  0
8     2  197  70  45  543  30.5  0.158  53  1
9     8  125  96   0    0   0.0  0.232  54  1
10    4  110  92   0    0  37.6  0.191  30  0
11   10  168  74   0    0  38.0  0.537  34  1
12   10  139  80   0    0  27.1  1.441  57  0
13    1  189  60  23  846  30.1  0.398  59  1
14    5  166  72  19  175  25.8  0.587  51  1
15    7  100   0   0    0  30.0  0.484  32  1
16    0  118  84  47  230  45.8  0.551  31  1
17    7  107  74   0    0  29.6  0.254  31  1
18    1  103  30  38   83  43.3  0.183  33  0
19    1  115  70  30   96  34.6  0.529  32  1
20    3  126  88  41  235  39.3  0.704  27  0
21    8   99  84   0    0  35.4  0.388  50  0
22    7  196  90   0    0  39.8  0.451  41  1
23    9  119  80  35    0  29.0  0.263  29  1
24   11  143  94  33  146  36.6  0.254  51  1
25   10  125  70  26  115  31.1  0.205  41  1
26    7  147  76   0    0  39.4  0.257  43  1
27    1   97  66  15  140  23.2  0.487  22  0
28   13  145  82  19  110  22.2  0.245  57  0
29    5  117  92   0    0  34.1  0.337  38  0
..   ..  ...  ..  ..  ...   ...    ...  .. ..
738   2   99  60  17  160  36.6  0.453  21  0
739   1  102  74   0    0  39.5  0.293  42  1
740  11  120  80  37  150  42.3  0.785  48  1
741   3  102  44  20   94  30.8  0.400  26  0
742   1  109  58  18  116  28.5  0.219  22  0
743   9  140  94   0    0  32.7  0.734  45  1
744  13  153  88  37  140  40.6  1.174  39  0
745  12  100  84  33  105  30.0  0.488  46  0
746   1  147  94  41    0  49.3  0.358  27  1
747   1   81  74  41   57  46.3  1.096  32  0
748   3  187  70  22  200  36.4  0.408  36  1
749   6  162  62   0    0  24.3  0.178  50  1
750   4  136  70   0    0  31.2  1.182  22  1
751   1  121  78  39   74  39.0  0.261  28  0
752   3  108  62  24    0  26.0  0.223  25  0
753   0  181  88  44  510  43.3  0.222  26  1
754   8  154  78  32    0  32.4  0.443  45  1
755   1  128  88  39  110  36.5  1.057  37  1
756   7  137  90  41    0  32.0  0.391  39  0
757   0  123  72   0    0  36.3  0.258  52  1
758   1  106  76   0    0  37.5  0.197  26  0
759   6  190  92   0    0  35.5  0.278  66  1
760   2   88  58  26   16  28.4  0.766  22  0
761   9  170  74  31    0  44.0  0.403  43  1
762   9   89  62   0    0  22.5  0.142  33  0
763  10  101  76  48  180  32.9  0.171  63  0
764   2  122  70  27    0  36.8  0.340  27  0
765   5  121  72  23  112  26.2  0.245  30  0
766   1  126  60   0    0  30.1  0.349  47  1
767   1   93  70  31    0  30.4  0.315  23  0

[768 rows x 9 columns]

In [4]:
# Data의 개략적 형태 확인
# pandas를 이용하였기 때문에, 읽힌 데이터가 DataFrame임을 확인할 수 있음
data.head(10)

0    1   2   3    4     5      6   7  8
0   6  148  72  35    0  33.6  0.627  50  1
1   1   85  66  29    0  26.6  0.351  31  0
2   8  183  64   0    0  23.3  0.672  32  1
3   1   89  66  23   94  28.1  0.167  21  0
4   0  137  40  35  168  43.1  2.288  33  1
5   5  116  74   0    0  25.6  0.201  30  0
6   3   78  50  32   88  31.0  0.248  26  1
7  10  115   0   0    0  35.3  0.134  29  0
8   2  197  70  45  543  30.5  0.158  53  1
9   8  125  96   0    0   0.0  0.232  54  1

In [5]:
# Data의 포인트 수와 변수의 수를 확인
data.shape

(768, 9)

In [6]:
# Data의 변수명을 정의하는 방법
variables = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data.columns = variables

In [7]:
data.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [8]:
data.describe()

preg        plas        pres        skin        test        mass  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

             pedi         age       class  
count  768.000000  768.000000  768.000000  
mean     0.471876   33.240885    0.348958  
std      0.331329   11.760232    0.476951  
min      0.078000   21.000000    0.000000  
25%      0.243750   24.000000    0.000000  
50%      0.372500   29.000000    0.000000  
75%      0.626250   41.000000    1.000000  
max      2.420000   81.000000    1.000000

In [9]:
# pandas.read_csv()에서 미리 변수명을 호출하는 방법도 있음
data2 = pd.read_csv('data/pima-indians-diabetes.data', names = variables)
data2.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

## Using numpy

In [10]:
# numpy.loadtxt를 이용
# delimiter를 정의하여 데이터를 불러들임
raw_data = open('data/pima-indians-diabetes.data', 'r')
data = np.loadtxt(raw_data, delimiter=',')

# 가급적 open을 한 데이터는 close하는 것이 좋음
raw_data.close()

In [11]:
# numpy를 이용해 읽은 데이터는 array임.
data

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [12]:
data.shape

(768, 9)

In [13]:
# with를 사용하면 데이터 close를 하지 않아도 편하게 사용 가능하다.
with open('data/pima-indians-diabetes.data', 'rb') as raw_data:
    data2 = np.loadtxt(raw_data, delimiter=',')

In [14]:
data2

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [15]:
# 앞에서 raw_data가 closed되었다는 에러 메시지가 나타날 것이다.
data3 = np.loadtxt(raw_data, delimiter=',')

ValueError: I/O operation on closed file.

# 2. Read the data file from a URL

## Using pandas 

In [17]:
# pandas는 매우 쉽게 url로부터 데이터를 읽어들임
url = "https://goo.gl/vhm1eU"
data = pd.read_csv(url, header = None)

HTTPError: HTTP Error 404: Not Found

In [18]:
data.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [19]:
data.shape

(768, 9)

## Using numpy 

In [20]:
# urllib.request.urlopen을 통해 url의 데이터를 읽을 수 있음
import urllib
raw_data = urllib.request.urlopen(url)
data = np.loadtxt(raw_data, delimiter=',')
raw_data.close()

HTTPError: HTTP Error 404: Not Found

In [19]:
data

array([[   6.   ,  148.   ,   72.   , ...,    0.627,   50.   ,    1.   ],
       [   1.   ,   85.   ,   66.   , ...,    0.351,   31.   ,    0.   ],
       [   8.   ,  183.   ,   64.   , ...,    0.672,   32.   ,    1.   ],
       ..., 
       [   5.   ,  121.   ,   72.   , ...,    0.245,   30.   ,    0.   ],
       [   1.   ,  126.   ,   60.   , ...,    0.349,   47.   ,    1.   ],
       [   1.   ,   93.   ,   70.   , ...,    0.315,   23.   ,    0.   ]])

In [20]:
data.shape

(768, 9)